using System;
using System.Drawing;
using System.Threading.Tasks;
using Xunit;
using ScreenRecorder.Core.Capture;
using ScreenRecorder.Core.Audio;
using ScreenRecorder.Core.Models;
using ScreenRecorder.Core.Pipeline;

namespace ScreenRecorder.Tests
{
    public class RecorderPipelineTests
    {
        [Fact]
        public void TestLockFreeQueueCapacityAndDropOldest()
        {
            var queue = new LockFreeQueue<VideoFrame>(5);
            for (int i = 0; i < 10; i++)
            {
                queue.Enqueue(new VideoFrame { TimestampMs = i });
            }

            Assert.Equal(5, queue.Count);
            
            // Should keep the latest items (5 through 9)
            queue.TryDequeue(out var frame);
            Assert.NotNull(frame);
            Assert.Equal(5, frame.TimestampMs);
        }

        [Fact]
        public async Task TestScreenCaptureEngineEmitsFrames()
        {
            var captureEngine = new ScreenCaptureEngine();
            int frameCount = 0;
            captureEngine.FrameCaptured += (sender, frame) =>
            {
                frameCount++;
            };

            captureEngine.StartCapture(60, new Rectangle(0, 0, 800, 600));
            await Task.Delay(150);
            captureEngine.StopCapture();

            Assert.True(frameCount > 0, "Capture engine should emit at least one frame.");
        }

        [Fact]
        public async Task TestAudioMixerEngineEmitsSamples()
        {
            var audioEngine = new AudioMixerEngine();
            int sampleCount = 0;
            audioEngine.AudioSampleCaptured += (sender, sample) =>
            {
                sampleCount++;
            };

            audioEngine.StartRecording();
            await Task.Delay(100);
            audioEngine.StopRecording();

            Assert.True(sampleCount > 0, "Audio mixer engine should emit audio samples.");
        }

        [Fact]
        public async Task TestPipelineManagerRecordingAndMuxing()
        {
            var captureEngine = new ScreenCaptureEngine();
            var audioEngine = new AudioMixerEngine();
            var pipeline = new RecorderPipelineManager(captureEngine, audioEngine);

            string testOutputFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "test_output.mkv");
            if (File.Exists(testOutputFile)) File.Delete(testOutputFile);

            pipeline.Start(testOutputFile, 60, new Rectangle(0, 0, 1920, 1080));
            await Task.Delay(200);
            await pipeline.StopAsync();

            Assert.True(File.Exists(testOutputFile), "Output file should be generated by the muxer pipeline.");
            var fileInfo = new FileInfo(testOutputFile);
            Assert.True(fileInfo.Length > 0, "Output file should not be empty.");

            if (File.Exists(testOutputFile)) File.Delete(testOutputFile);
        }
    }
}
